#!/bin/bash
# Generate the documentation's reference pages from the toolchain itself.
#
# Nothing here is written by hand. A hand-copied command table is out of date
# by the next release and nobody notices until a reader tries one; asking the
# compiler what it supports is the only version that stays true.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
OUT="$ROOT/docs-site/src"
OPENEPL="${OPENEPL:-$ROOT/target/release/openepl}"
[ -x "$OPENEPL" ] || OPENEPL="$ROOT/target/debug/openepl"
[ -x "$OPENEPL" ] || { echo "build openepl first (cargo build)" >&2; exit 1; }

banner='<!-- Generated by tools/gen-docs.sh — do not edit; edit the toolchain. -->'

# --- commands -------------------------------------------------------------
{
    echo "$banner"
    echo
    cat <<'MD'
# Commands

Every command the core runtime provides, plus those contributed by the `ui`
library. Call one as a statement with `call`, or use its result in an
expression when it returns a value.

```
call print_text("hello")            # as a statement
let n: int = max_int(3, 9)          # as an expression
```

MD
    printf '| Command | Parameters | Returns |\n| --- | --- | --- |\n'
    "$OPENEPL" commands --use ui | sed -n 's/^command: //p' | sort | while read -r line; do
        name="${line%%(*}"
        rest="${line#*(}"
        params="${rest%%)*}"
        ret="${line##*) -> }"
        [ "$ret" = "$line" ] && ret="—"
        printf '| `%s` | %s | %s |\n' "$name" "${params:-—}" "$ret"
    done
} > "$OUT/reference-commands.md"

# --- components -----------------------------------------------------------
{
    echo "$banner"
    echo
    cat <<'MD'
# Components

The visual components the `ui` library provides. Place one in a form, set its
properties, and bind its events to subroutines — from the designer, or by
writing it out directly.

MD
    for c in $("$OPENEPL" commands --use ui | sed -n 's/^component: //p' | sort); do
        printf '## %s\n\n' "$c"
        printf '| Property | Type |\n| --- | --- |\n'
        "$OPENEPL" commands --use ui | sed -n "s/^property: $c //p" |
            while read -r name ty; do printf '| `%s` | %s |\n' "$name" "$ty"; done
        events=$("$OPENEPL" commands --use ui | sed -n "s/^event: $c //p" | sed 's/^/`/; s/$/`/' | paste -sd', ')
        printf '\n**Events:** %s\n\n' "${events:-none}"
    done
} > "$OUT/reference-components.md"

# --- templates ------------------------------------------------------------
{
    echo "$banner"
    echo
    cat <<'MD'
# Project templates

`openepl new <template> <directory>` creates a project from one of these. Each
one compiles and runs as it stands.

MD
    printf '| Template | Builds | What you get |\n| --- | --- | --- |\n'
    "$OPENEPL" templates | awk '
        /^template: / { split($0, a, " "); id=a[2]; target[id]=a[3]; order[++n]=id }
        /^name: /     { split($0, a, " "); id=a[2]; $1=""; $2=""; sub(/^  /,""); name[id]=$0 }
        /^desc: /     { split($0, a, " "); id=a[2]; $1=""; $2=""; sub(/^  /,""); desc[id]=$0 }
        END { for (i=1; i<=n; i++) { id=order[i];
                printf "| `%s` | `%s` | %s |\n", id, target[id], desc[id] } }'
} > "$OUT/reference-templates.md"

# --- command line ---------------------------------------------------------
{
    echo "$banner"
    echo
    cat <<'MD'
# Command line

```text
MD
    "$OPENEPL" --help 2>&1
    cat <<'MD'
```

## Building

`openepl build` compiles a module to a native artifact and `openepl run`
builds it and runs it straight away.

```sh
openepl build app.oir                      # ./app
openepl build app.oir -o build/app         # somewhere else
openepl build lib.oir --target sharedlib   # a different artifact
openepl run app.oir
```

`--target` overrides whatever the module declares, so one source can be built
as a program or as a library without editing it. See
[Build targets](./build-targets.md).

## Starting a project

```sh
openepl templates                # what you can create
openepl new gui-app my-app       # create it
openepl new gui-app my-app --name my_module
```

The module is named after the directory unless `--name` says otherwise;
characters that cannot appear in an identifier are replaced.

## Finding out what exists

```sh
openepl commands                 # the core runtime
openepl commands --use ui        # and the visual components
```

## Editor support

`openepl lsp` speaks the Language Server Protocol over stdin and stdout. It is
not run by hand — an editor starts it. See
[Editors and the language server](./editors.md).
MD
} > "$OUT/cli.md"

echo "generated: reference-commands.md reference-components.md reference-templates.md cli.md"
