#!/bin/bash
# Generate the documentation's reference pages from the toolchain itself.
#
# Nothing here is written by hand. A hand-copied command table is out of date
# by the next release and nobody notices until a reader tries one; asking the
# compiler what it supports is the only version that stays true.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
OUT="$ROOT/docs-site/src"
OPENEPL="${OPENEPL:-$ROOT/target/release/openepl}"
[ -x "$OPENEPL" ] || OPENEPL="$ROOT/target/debug/openepl"
[ -x "$OPENEPL" ] || { echo "build openepl first (cargo build)" >&2; exit 1; }

banner='<!-- Generated by tools/gen-docs.sh — do not edit; edit the toolchain. -->'

# --- commands -------------------------------------------------------------
# Every library under libs/ is documented, discovered rather than listed, so a
# new library appears here the moment it exists. `hello` is excluded: it is a
# worked example for library authors, not something a program should `use`.
LIBS=()
for d in "$ROOT"/libs/*/; do
    name="$(basename "$d")"
    [ "$name" = "hello" ] && continue
    LIBS+=("$name")
done

# A command's library is not in the output, so it is recovered by difference:
# what `--use X` lists that core alone does not.
"$OPENEPL" commands | sed -n 's/^command: //p' | sort > /tmp/openepl-core-cmds.$$

emit_table() {
    printf '| Command | Parameters | Returns |\n| --- | --- | --- |\n'
    sort | while read -r line; do
        name="${line%%(*}"
        rest="${line#*(}"
        params="${rest%%)*}"
        ret="${line##*) -> }"
        [ "$ret" = "$line" ] && ret="—"
        printf '| `%s` | %s | %s |\n' "$name" "${params:-—}" "$ret"
    done
}

{
    echo "$banner"
    echo
    cat <<'MD'
# Commands

Call one as a statement with `call`, or use its result in an expression when it
returns a value.

```
call print_text("hello")            # as a statement
let n: int = max_int(3, 9)          # as an expression
```

The core commands are always available. The rest come from a support library,
which a module asks for by name:

```
module report
use file

sub main
  call print_text(file_read_text("notes.txt"))
end
```

## Reporting failure

A command that can fail returns a sentinel — `0` for a handle, `-1` for a count
or size, `""` for text, `false` for a yes/no — and leaves the reason in the
error slot, which `last_error_code()` and `last_error_text()` read.

```
let h: int = file_open("notes.txt", "read")
if h = 0
  call print_text(last_error_text())
end
```

A successful command clears the slot, so a code left over from earlier can
never be mistaken for a fresh failure. That is also what makes `false` precise:
false with code `0` is a genuine no, false with a non-zero code is a failure.

## Core

MD
    cat /tmp/openepl-core-cmds.$$ | emit_table
    for l in "${LIBS[@]}"; do
        printf '\n## %s\n\n`use %s`\n\n' "$l" "$l"
        "$OPENEPL" commands --use "$l" | sed -n 's/^command: //p' | sort |
            comm -13 /tmp/openepl-core-cmds.$$ - | emit_table
    done
} > "$OUT/reference-commands.md"
rm -f /tmp/openepl-core-cmds.$$

# --- components -----------------------------------------------------------
{
    echo "$banner"
    echo
    cat <<'MD'
# Components

The visual components the `ui` library provides. Place one in a form, set its
properties, and bind its events to subroutines — from the designer, or by
writing it out directly.

MD
    for c in $("$OPENEPL" commands --use ui | sed -n 's/^component: //p' | sort); do
        printf '## %s\n\n' "$c"
        printf '| Property | Type |\n| --- | --- |\n'
        "$OPENEPL" commands --use ui | sed -n "s/^property: $c //p" |
            while read -r name ty; do printf '| `%s` | %s |\n' "$name" "$ty"; done
        events=$("$OPENEPL" commands --use ui | sed -n "s/^event: $c //p" | sed 's/^/`/; s/$/`/' | paste -sd', ')
        printf '\n**Events:** %s\n\n' "${events:-none}"
    done
} > "$OUT/reference-components.md"

# --- templates ------------------------------------------------------------
{
    echo "$banner"
    echo
    cat <<'MD'
# Project templates

`openepl new <template> <directory>` creates a project from one of these. Each
one compiles and runs as it stands.

MD
    printf '| Template | Builds | What you get |\n| --- | --- | --- |\n'
    "$OPENEPL" templates | awk '
        /^template: / { split($0, a, " "); id=a[2]; target[id]=a[3]; order[++n]=id }
        /^name: /     { split($0, a, " "); id=a[2]; $1=""; $2=""; sub(/^  /,""); name[id]=$0 }
        /^desc: /     { split($0, a, " "); id=a[2]; $1=""; $2=""; sub(/^  /,""); desc[id]=$0 }
        END { for (i=1; i<=n; i++) { id=order[i];
                printf "| `%s` | `%s` | %s |\n", id, target[id], desc[id] } }'
} > "$OUT/reference-templates.md"

# --- command line ---------------------------------------------------------
{
    echo "$banner"
    echo
    cat <<'MD'
# Command line

```text
MD
    "$OPENEPL" --help 2>&1
    cat <<'MD'
```

## Building

`openepl build` compiles a module to a native artifact and `openepl run`
builds it and runs it straight away.

```sh
openepl build app.oir                      # ./app
openepl build app.oir -o build/app         # somewhere else
openepl build lib.oir --target sharedlib   # a different artifact
openepl run app.oir
```

`--target` overrides whatever the module declares, so one source can be built
as a program or as a library without editing it. See
[Build targets](./build-targets.md).

## Starting a project

```sh
openepl templates                # what you can create
openepl new gui-app my-app       # create it
openepl new gui-app my-app --name my_module
```

The module is named after the directory unless `--name` says otherwise;
characters that cannot appear in an identifier are replaced.

## Finding out what exists

```sh
openepl commands                 # the core runtime
openepl commands --use file      # and what a library adds
```

## Editor support

`openepl lsp` speaks the Language Server Protocol over stdin and stdout. It is
not run by hand — an editor starts it. See
[Editors and the language server](./editors.md).
MD
} > "$OUT/cli.md"

echo "generated: reference-commands.md reference-components.md reference-templates.md cli.md"
