#!/bin/bash
# Generate the documentation's reference pages from the toolchain itself.
#
# Nothing here is written by hand. A hand-copied command table is out of date
# by the next release and nobody notices until a reader tries one; asking the
# compiler what it supports is the only version that stays true.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
OUT="$ROOT/docs-site/src"
OPENEPL="${OPENEPL:-$ROOT/target/release/openepl}"
[ -x "$OPENEPL" ] || OPENEPL="$ROOT/target/debug/openepl"
[ -x "$OPENEPL" ] || { echo "build openepl first (cargo build)" >&2; exit 1; }

banner='<!-- Generated by tools/gen-docs.sh — do not edit; edit the toolchain. -->'

# --- commands -------------------------------------------------------------
# Every kit is documented, discovered rather than listed, so a new one appears
# here the moment it exists. The list comes from `openepl kits` rather than a
# glob over libs/ so that an installed kit is documented exactly when it is
# usable — one resolution, not a second one that drifts from it. `hello` is
# excluded: it is a worked example for library authors, not something a program
# should `use`.
LIBS=()
while read -r name _version _tier; do
    [ "$name" = "hello" ] && continue
    LIBS+=("$name")
# Sorted by name: `order` is where a kit sits in a toolbox, which is not how a
# reader looks something up in a reference.
done < <("$OPENEPL" kits | sed -n 's/^kit: //p' | sort)

# A command's library is not in the output, so it is recovered by difference:
# what `--use X` lists that core alone does not.
"$OPENEPL" commands | sed -n 's/^command: //p' | sort > /tmp/openepl-core-cmds.$$

emit_table() {
    printf '| Command | Parameters | Returns |\n| --- | --- | --- |\n'
    sort | while read -r line; do
        name="${line%%(*}"
        rest="${line#*(}"
        params="${rest%%)*}"
        ret="${line##*) -> }"
        [ "$ret" = "$line" ] && ret="—"
        printf '| `%s` | %s | %s |\n' "$name" "${params:-—}" "$ret"
    done
}

{
    echo "$banner"
    echo
    cat <<'MD'
# Commands

Call one as a statement with `call`, or use its result in an expression when it
returns a value.

```
call print_text("hello")            # as a statement
let n: int = max_int(3, 9)          # as an expression
```

The core commands are always available. The rest come from a support library,
which a module asks for by name:

```
module report
use file

sub main
  call print_text(file_read_text("notes.txt"))
end
```

## Reporting failure

A command that can fail returns a sentinel — `0` for a handle, `-1` for a count
or size, `""` for text, `false` for a yes/no — and leaves the reason in the
error slot, which `last_error_code()` and `last_error_text()` read.

```
let h: int = file_open("notes.txt", "read")
if h = 0
  call print_text(last_error_text())
end
```

A successful command clears the slot, so a code left over from earlier can
never be mistaken for a fresh failure. That is also what makes `false` precise:
false with code `0` is a genuine no, false with a non-zero code is a failure.

## Core

MD
    cat /tmp/openepl-core-cmds.$$ | emit_table
    for l in "${LIBS[@]}"; do
        printf '\n## %s\n\n`use %s`\n\n' "$l" "$l"
        "$OPENEPL" commands --use "$l" | sed -n 's/^command: //p' | sort |
            comm -13 /tmp/openepl-core-cmds.$$ - | emit_table
    done
} > "$OUT/reference-commands.md"
rm -f /tmp/openepl-core-cmds.$$

# --- components -----------------------------------------------------------
# Grouped by the library that declares them, and discovered the same way the
# command tables are. A component is no longer a `ui` thing: core ships `timer`
# and `net` ships `httpserver`, so a page built from one library's list would
# quietly omit whatever the newest one added.
{
    echo "$banner"
    echo
    cat <<'MD'
# Components

A component has properties you set and events you bind to subroutines — from
the designer, or by writing it out directly. Most draw a rectangle; some, like
`timer` and `httpserver`, have no pixels at all and are declared at module
level rather than inside a form.

MD
    "$OPENEPL" commands | sed -n 's/^component: //p' | sort > /tmp/openepl-core-comps.$$

    emit_components() {   # $1 = heading, $2… = `commands` invocation output file
        local list
        list=$(sed -n 's/^component: //p' "$2" | sort | comm -13 "$3" -)
        [ -n "$list" ] || return 0
        printf '\n# %s\n\n' "$1"
        for c in $list; do
            printf '## %s\n\n' "$c"
            printf '| Property | Type |\n| --- | --- |\n'
            sed -n "s/^property: $c //p" "$2" |
                while read -r name ty; do printf '| `%s` | %s |\n' "$name" "$ty"; done
            events=$(sed -n "s/^event: $c //p" "$2" | sed 's/^/`/; s/$/`/' | paste -sd', ')
            printf '\n**Events:** %s\n\n' "${events:-none}"
        done
    }

    : > /tmp/openepl-empty.$$
    "$OPENEPL" commands > /tmp/openepl-core-all.$$
    emit_components "Core" /tmp/openepl-core-all.$$ /tmp/openepl-empty.$$
    for l in "${LIBS[@]}"; do
        "$OPENEPL" commands --use "$l" > /tmp/openepl-lib-all.$$
        emit_components "$l" /tmp/openepl-lib-all.$$ /tmp/openepl-core-comps.$$
    done
    rm -f /tmp/openepl-core-comps.$$ /tmp/openepl-core-all.$$ /tmp/openepl-lib-all.$$ /tmp/openepl-empty.$$
} > "$OUT/reference-components.md"

# --- templates ------------------------------------------------------------
{
    echo "$banner"
    echo
    cat <<'MD'
# Project templates

`openepl new <template> <directory>` creates a project from one of these. Each
one compiles and runs as it stands.

MD
    printf '| Template | Builds | What you get |\n| --- | --- | --- |\n'
    "$OPENEPL" templates | awk '
        /^template: / { split($0, a, " "); id=a[2]; target[id]=a[3]; order[++n]=id }
        /^name: /     { split($0, a, " "); id=a[2]; $1=""; $2=""; sub(/^  /,""); name[id]=$0 }
        /^desc: /     { split($0, a, " "); id=a[2]; $1=""; $2=""; sub(/^  /,""); desc[id]=$0 }
        END { for (i=1; i<=n; i++) { id=order[i];
                printf "| `%s` | `%s` | %s |\n", id, target[id], desc[id] } }'
} > "$OUT/reference-templates.md"

# --- command line ---------------------------------------------------------
{
    echo "$banner"
    echo
    cat <<'MD'
# Command line

```text
MD
    "$OPENEPL" --help 2>&1
    cat <<'MD'
```

## Building

`openepl build` compiles a module to a native artifact and `openepl run`
builds it and runs it straight away.

```sh
openepl build app.oir                      # ./app
openepl build app.oir -o build/app         # somewhere else
openepl build lib.oir --target sharedlib   # a different artifact
openepl run app.oir
```

`--target` overrides whatever the module declares, so one source can be built
as a program or as a library without editing it. See
[Build targets](./build-targets.md).

## Starting a project

```sh
openepl templates                # what you can create
openepl new gui-app my-app       # create it
openepl new gui-app my-app --name my_module
```

The module is named after the directory unless `--name` says otherwise;
characters that cannot appear in an identifier are replaced.

## Finding out what exists

```sh
openepl commands                 # the core runtime
openepl commands --use file      # and what a library adds
```

## Reading a project from a tool

`openepl inspect <file.oir>` is how OpenEPL Studio learns what a file holds;
it is the only reader of a project file, so a tool that wants the same
knowledge asks it rather than parsing the source. The output is one fact per
line, `kind: rest`, in file order:

| Line | Meaning |
| --- | --- |
| `module: <name>` | the module's name |
| `use: <lib>` | a `use` line |
| `sub: <name>` | a subroutine; `subsig: <name> (<params>) <ret>` follows when it takes or returns anything |
| `form: <name> span=<first>..<last>` | the form, and the 1-based lines its `form … end` block occupies |
| `component: <id> <type>` | a component inside the form |
| `modcomponent: <id> <type> span=<first>..<last>` | a component declared at module level — a `timer`, an `httpserver` — with the lines of its block |
| `prop: <id> <name> <value>` | a property of the form or of the component named by `<id>` |
| `handler: <id> <event> <sub>` | an event binding |

A `prop:` value is always on its one line: a newline in it is written `\n`, a
NUL `\0`, and a backslash `\\`; nothing else is escaped. A reader reverses
exactly those three. A `modcomponent:` without a `span=` is one the toolchain
could not place, and a tool that splices the file should treat it as not yet
written rather than guess.

`openepl commands` is read the same way. Beside each `component: <type>` line
is `kind: <type> visual` or `kind: <type> nonvisual`, and a `property:` line
whose editor is not the plain one its type implies is followed by
`editor: <type> <property> <hint>` — `color`, `file`, `font` or `multiline`.
New line kinds are added; the existing ones do not change shape, so a reader
that skips what it does not know keeps working.

## Kits

A kit is a support library plus what an IDE needs to present it. `openepl kits`
lists the ones resolution found, each with its version and where it came from —
`project` for a `kits/` directory beside your source, `user` for
`~/.openepl/kits/`, `bundled` for the ones shipped with the toolchain. The
first match of a name wins, in that order.

```sh
openepl kits                     # what is installed, and from where
openepl kit add ./mykit          # install a directory
openepl kit add mykit.tar.gz     # or a tarball
```

See [Kits](./kits.md).

## Editor support

`openepl lsp` speaks the Language Server Protocol over stdin and stdout. It is
not run by hand — an editor starts it. See
[Editors and the language server](./editors.md).
MD
} > "$OUT/cli.md"

echo "generated: reference-commands.md reference-components.md reference-templates.md cli.md"
