//! The C header a library build writes beside its artifact.
//!
//! A shared or static library exports every subroutine under its plain name
//! (backend/src/lib.rs, the library path), so a C or C++ host can call them —
//! but only if it knows the prototypes. Declaring them by hand is where a host
//! and its library drift apart: the header is generated from the same IR the
//! backend lowered, so what it declares is what was linked.
//!
//! The shape is the one a hand-written Windows DLL header has, and for the
//! same reasons: an `extern "C"` guard so C++ sees C linkage, and an export
//! macro that is `dllexport` while the DLL is being built, `dllimport` in a
//! consumer, and default visibility elsewhere. The build never defines the
//! `_EXPORTS` symbol itself — the library's own objects come out of LLVM IR,
//! not from this header — so in practice the macro reads `dllimport`, which
//! is what a consumer wants.

use std::fmt::Write;
use std::path::{Path, PathBuf};

use openepl_ir::{Module, Sub, Target, Ty};

/// The C spelling of an exported type, or `None` when C has no name for it.
///
/// Each answer is the C view of what `llvm_ty` in backend/src/lib.rs lowers
/// the type to, since the wrapper is called with exactly that signature:
/// `bool` is `int32_t` because the backend widens it to `i32` (a C `_Bool`
/// is one byte and would marshal wrong); `int64` is `int64_t` rather than
/// `long` because `long` is 32 bits on Windows. Text is a NUL-terminated
/// string, `NULL` meaning empty. A byte-set, an array, a record and a
/// dictionary are pointers to runtime-owned objects a host cannot build or
/// read without the runtime, so they get no prototype at all: a `void *` a
/// host could not fill in honestly would be worse than a comment saying why.
pub fn c_type(t: Ty) -> Option<&'static str> {
    match t {
        Ty::Int => Some("int32_t"),
        Ty::Int64 => Some("int64_t"),
        Ty::Double => Some("double"),
        Ty::Bool => Some("int32_t"),
        Ty::Text => Some("const char *"),
        // A raw pointer is the one aggregate-shaped type C has an honest name
        // for: it IS a `void *`, with no runtime-owned object behind it, so an
        // exported sub taking or returning one gets a real prototype.
        Ty::Ptr => Some("void *"),
        // `byte`, `int16` and `float` are c-record field widths, and an inline
        // array is a c-record field shape: none is ever a standalone exported
        // type — no sub signature carries one — so none has a C prototype
        // spelling here, alongside the runtime-owned aggregates.
        // An optional is a local's type: no sub signature carries one, so it
        // has no C spelling either.
        Ty::Optional(_)
        | Ty::Byte
        | Ty::Int16
        | Ty::Float
        | Ty::CArray(_)
        | Ty::Bytes
        | Ty::Array(_)
        | Ty::Record(_)
        | Ty::Dict(_)
        | Ty::AnyArray
        | Ty::AnyElem
        | Ty::AnyDict => None,
    }
}

/// The header's macro prefix: the module name as C would like to shout it.
/// `greet` becomes `GREET_API` and `GREET_EXPORTS`; a character C would not
/// take in an identifier becomes `_`, so any module name yields a macro.
pub fn macro_prefix(module_name: &str) -> String {
    let mut s: String = module_name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect();
    if s.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        s.insert(0, '_');
    }
    s
}

/// Where the header goes when nobody said: `<module>.h` beside the artifact.
/// The module's name rather than the artifact's stem, because `-o libgreet.so`
/// should still give `greet.h` — the name the exports are already under.
pub fn default_path(out_bin: &Path, module_name: &str) -> PathBuf {
    out_bin
        .parent()
        .unwrap_or(Path::new("."))
        .join(format!("{module_name}.h"))
}

/// The header text for a library module: one prototype per exported
/// subroutine, in declaration order, after `<module>_init`.
pub fn render(m: &Module) -> String {
    let prefix = macro_prefix(&m.name);
    let api = format!("{prefix}_API");
    let mut out = String::new();
    writeln!(
        out,
        "/* {}.h — generated by OpenEPL from module `{}`.",
        m.name, m.name
    )
    .unwrap();
    writeln!(
        out,
        " * Do not edit; regenerate by building the .oir source. */"
    )
    .unwrap();
    writeln!(out, "#pragma once").unwrap();
    writeln!(out, "#include <stdint.h>").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#ifdef __cplusplus").unwrap();
    writeln!(out, "extern \"C\" {{").unwrap();
    writeln!(out, "#endif").unwrap();
    writeln!(out).unwrap();
    // A static library's symbols are linked in, not imported: `dllimport` on
    // them makes a Windows host look for `__imp_add` in an import library
    // that does not exist. The header says what it was built as, through
    // the `_STATIC` switch a hand-written header would also offer.
    if m.target() == Target::StaticLib {
        writeln!(
            out,
            "/* Built as a static library: nothing is imported from a DLL. */"
        )
        .unwrap();
        writeln!(out, "#ifndef {prefix}_STATIC").unwrap();
        writeln!(out, "#  define {prefix}_STATIC").unwrap();
        writeln!(out, "#endif").unwrap();
        writeln!(out).unwrap();
    }
    writeln!(out, "#if defined({prefix}_STATIC)").unwrap();
    writeln!(out, "#  define {api}").unwrap();
    writeln!(out, "#elif defined(_WIN32)").unwrap();
    writeln!(
        out,
        "#  ifdef {prefix}_EXPORTS /* defined when building the DLL itself */"
    )
    .unwrap();
    writeln!(out, "#    define {api} __declspec(dllexport)").unwrap();
    writeln!(out, "#  else").unwrap();
    writeln!(out, "#    define {api} __declspec(dllimport)").unwrap();
    writeln!(out, "#  endif").unwrap();
    writeln!(out, "#else").unwrap();
    writeln!(
        out,
        "#  define {api} __attribute__((visibility(\"default\")))"
    )
    .unwrap();
    writeln!(out, "#endif").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "/* Types: `int` and `bool` are int32_t (a bool is 0 or 1), `int64` is"
    )
    .unwrap();
    writeln!(
        out,
        " * int64_t, `double` is double, `text` is a NUL-terminated string where"
    )
    .unwrap();
    writeln!(
        out,
        " * NULL means empty. Text a subroutine returns is owned by the library:"
    )
    .unwrap();
    writeln!(out, " * copy it if you keep it, and never free it. */").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "{api} void {}_init(void); /* initialises module variables; call once, first */",
        m.name
    )
    .unwrap();

    let mut inexpressible: Vec<&Sub> = Vec::new();
    for sub in m.subs() {
        match prototype(sub, &api) {
            Some(p) => writeln!(out, "{p}").unwrap(),
            None => inexpressible.push(sub),
        }
    }
    if !inexpressible.is_empty() {
        writeln!(out).unwrap();
        writeln!(
            out,
            "/* Exported, but with a type C cannot name (a byte-set, an array, a"
        )
        .unwrap();
        writeln!(
            out,
            " * record or a dictionary is a pointer to a runtime-owned object):"
        )
        .unwrap();
        for sub in inexpressible {
            writeln!(out, " *   {}", signature(sub)).unwrap();
        }
        writeln!(out, " */").unwrap();
    }

    writeln!(out).unwrap();
    writeln!(out, "#ifdef __cplusplus").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out, "#endif").unwrap();
    out
}

/// `GREET_API int32_t add(int32_t a, int32_t b);`, or `None` when any type in
/// the signature has no C spelling.
fn prototype(sub: &Sub, api: &str) -> Option<String> {
    let ret = match sub.ret {
        None => "void",
        Some(t) => c_type(t)?,
    };
    let params = if sub.params.is_empty() {
        "void".to_string()
    } else {
        let mut parts = Vec::with_capacity(sub.params.len());
        for (name, ty) in &sub.params {
            let c = c_type(*ty)?;
            // `const char *name`, not `const char * name`: the pointer binds
            // to the name in C, and the header should read like one.
            let sep = if c.ends_with('*') { "" } else { " " };
            parts.push(format!("{c}{sep}{name}"));
        }
        parts.join(", ")
    };
    let sep = if ret.ends_with('*') { "" } else { " " };
    Some(format!("{api} {ret}{sep}{}({params});", sub.name))
}

/// The OpenEPL spelling of a signature, for the comment that lists what the
/// header could not declare.
fn signature(sub: &Sub) -> String {
    let params = sub
        .params
        .iter()
        .map(|(n, t)| format!("{n}: {}", t.as_str()))
        .collect::<Vec<_>>()
        .join(", ");
    match sub.ret {
        None => format!("{}({params})", sub.name),
        Some(t) => format!("{}({params}): {}", sub.name, t.as_str()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn module(src: &str) -> Module {
        openepl_ir::parse(src).expect("parse")
    }

    #[test]
    fn every_scalar_type_has_its_abi_spelling() {
        let m = module(
            "module greet\ntarget sharedlib\n\
             sub add(a: int, b: int): int\n  return a + b\nend\n\
             sub big(n: int64): int64\n  return n\nend\n\
             sub half(x: double): double\n  return x / 2.0\nend\n\
             sub yes(b: bool): bool\n  return b\nend\n\
             sub hello(name: text): text\n  return \"hi \" + name\nend\n\
             sub nothing\n  call print_text(\"x\")\nend\n",
        );
        let h = render(&m);
        assert!(h.contains("GREET_API void greet_init(void);"), "{h}");
        assert!(
            h.contains("GREET_API int32_t add(int32_t a, int32_t b);"),
            "{h}"
        );
        assert!(h.contains("GREET_API int64_t big(int64_t n);"), "{h}");
        assert!(h.contains("GREET_API double half(double x);"), "{h}");
        assert!(h.contains("GREET_API int32_t yes(int32_t b);"), "{h}");
        assert!(
            h.contains("GREET_API const char *hello(const char *name);"),
            "{h}"
        );
        assert!(h.contains("GREET_API void nothing(void);"), "{h}");
        assert!(h.contains("ifdef GREET_EXPORTS"), "{h}");
        assert!(h.contains("extern \"C\""), "{h}");
        assert!(
            !h.contains("cannot name"),
            "nothing should be inexpressible: {h}"
        );
        assert!(
            !h.contains("define GREET_STATIC"),
            "a shared library is not static: {h}"
        );
    }

    #[test]
    fn a_sub_with_an_aggregate_is_listed_not_declared() {
        let m = module(
            "module bag\ntarget staticlib\n\
             sub total(xs: int[]): int\n  return count(xs)\nend\n\
             sub plain: int\n  return 1\nend\n",
        );
        let h = render(&m);
        assert!(h.contains("BAG_API int32_t plain(void);"), "{h}");
        // Static: a Windows host must not go looking for `__imp_plain`.
        assert!(h.contains("#  define BAG_STATIC"), "{h}");
        assert!(
            h.contains("#if defined(BAG_STATIC)\n#  define BAG_API\n"),
            "{h}"
        );
        assert!(!h.contains("BAG_API int32_t total"), "{h}");
        assert!(h.contains(" *   total(xs: int[]): int"), "{h}");
    }

    #[test]
    fn macro_prefix_is_a_c_identifier() {
        assert_eq!(macro_prefix("greet"), "GREET");
        assert_eq!(macro_prefix("my-lib.v2"), "MY_LIB_V2");
        assert_eq!(macro_prefix("3d"), "_3D");
    }

    #[test]
    fn header_is_named_after_the_module_beside_the_artifact() {
        let p = default_path(Path::new("/out/libgreet.so"), "greet");
        assert_eq!(p, PathBuf::from("/out/greet.h"));
        assert_eq!(
            default_path(Path::new("greet.dll"), "greet"),
            PathBuf::from("greet.h")
        );
    }
}
